name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Publish to crates.io
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    needs: publish-crates
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            suffix: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: ''

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install musl tools
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: sudo apt-get install -y musl-tools

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Package
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          7z a ../../../rush-${{ matrix.target }}.zip rush-build${{ matrix.suffix }} rush${{ matrix.suffix }}
        else
          tar czvf ../../../rush-${{ matrix.target }}.tar.gz rush-build${{ matrix.suffix }} rush${{ matrix.suffix }}
        fi

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rush-${{ matrix.target }}.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Extract version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update Homebrew formula
      uses: mislav/bump-homebrew-formula-action@v3
      with:
        formula-name: rush-build
        formula-path: Formula/rush-build.rb
        homebrew-tap: iPeluwa/homebrew-tap
        download-url: https://github.com/iPeluwa/rush/releases/download/v${{ steps.version.outputs.VERSION }}/rush-x86_64-apple-darwin.tar.gz
        commit-message: |
          rush-build ${{ steps.version.outputs.VERSION }}

          Created by https://github.com/mislav/bump-homebrew-formula-action
      env:
        COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
